### PR TITLE
Return null for non-existing values in the XML/JSON response

### LINKED ISSUE #25: Make XmlResponseTests more easy to read
To make the test better readable we should try to build up the expected data as a data structure and then use `assertEquals`. This will also give us a nice diff view of expected and actual data when the test fails.

### PR DESCRIPTION
**Pull request by TheKeymaster**
If values to not exist, they may return `null` instead of `''`, `0` or `0.0`.

 * Introduce `ResponseHelper`
    * Checks if properties exist and returns `null` if they don't.
    * Properties that contain any values what are empty, will also return `null`.

This change was made to make sure if I call:

```php
$filters = $xmlResponse->getFilters();

foreach ($filters as $filter) {
    foreach ($filter->getItems() as $item) {
        // Before: $test = 0
        // Now: $test = null
        $test = $item->getFrequency() 
    }
}
```

This meant that some filters returned values, that they did not even have. This is now fixed.

Fixes #25.

### CODE REVIEW

**Comment by TheKeymaster** [comment]
@TheKeymaster (myself) make sure to take care of this comment: https://github.com/TheKeymaster/findologic-api/pull/13/files/bf5b931d893525d129d9237e33a8f48019aea9e3#r244041605.

**Comment by TheKeymaster** [comment]
@TheKeymaster please make sure to respect [this comment](https://github.com/TheKeymaster/findologic-api/pull/13/files#r244041605) before merging.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+     * Gets a property from an object.
+     *
+     * @param mixed $obj
+     * @param string $property
+     * @param null|string $type Convert value to another type. Optional.
+     * @param bool $emptyValueIsAllowed If true, values that are 0 or 0.0 are allowed.
+     *
+     * @return mixed|null Returns the property value or null if it does not exist.
+     */
+    public static function getProperty($obj, $property, $type = null, $emptyValueIsAllowed = false)
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: Would it be a good idea to check if `$type` is one of a limited number of permissible types, and providing constants for them?

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 2]
```diff
@@ -0,0 +1,51 @@
+<?php
+
+namespace FINDOLOGIC\Helpers;
+
+class ResponseHelper
+{
+    /**
+     * Gets a property from an object.
+     *
+     * @param mixed $obj
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: Is not `mixed`, but `stdClass`.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 3]
```diff
@@ -0,0 +1,51 @@
+<?php
+
+namespace FINDOLOGIC\Helpers;
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: The used namespace makes this project look global/one level higher than the other PHP projects. `FINDOLOGIC` should be followed by a project-specific namespace part.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+     * @param mixed $obj
+     * @param string $property
+     * @param null|string $type Convert value to another type. Optional.
+     * @param bool $emptyValueIsAllowed If true, values that are 0 or 0.0 are allowed.
+     *
+     * @return mixed|null Returns the property value or null if it does not exist.
+     */
+    public static function getProperty($obj, $property, $type = null, $emptyValueIsAllowed = false)
+    {
+        if (!property_exists($obj, $property)) {
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: Is it wise to just return `null` if something doesn't exist? Something being missing could be indicative of a bug. For truly optional things, perhaps having a way to provide a default value would be an improvement.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+        $propertyValue = $obj->{$property};
+        if ($type === null) {
+            return $propertyValue;
+        }
+
+        settype($propertyValue, $type);
+
+        // Check for empty after the property has been casted to submitted the type.
+        if (!$emptyValueIsAllowed && self::isEmpty($propertyValue)) {
+            return null;
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: This seems like a bug/error scenario. Is it a good idea to silently ignore it by returning `null`?

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+     * will more likely not be empty when you expect it to be. Values like literal string '0' is therefore allowed and
+     * is considered as "not empty".
+     *
+     * @param mixed $v
+     *
+     * @return bool
+     */
+    private static function isEmpty($v)
+    {
+        return ($v === '' || $v === 0 || $v === 0.0);
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: Redundant parentheses.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+    /**
+     * Checks if a variable is empty. Please take note that this function isn't like the PHP function, so a variable
+     * will more likely not be empty when you expect it to be. Values like literal string '0' is therefore allowed and
+     * is considered as "not empty".
+     *
+     * @param mixed $v
+     *
+     * @return bool
+     */
+    private static function isEmpty($v)
```
Comment (howard) [inline src/FINDOLOGIC/Helpers/ResponseHelper.php]: `$v` is not an expressive parameter name.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 1 above)
Comment (howard) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: Thinking further about this, maybe the best solution is to make this method private and call it from several public methods for each of the permitted types, indicating the type in the name, e.g. something like `getStringProperty` and `getIntProperty`.

File: src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php [hunk 8]
```diff
@@ -2,14 +2,15 @@
 
 namespace FINDOLOGIC\Objects\XmlResponseObjects;
 
+use FINDOLOGIC\Helpers\ResponseHelper;
 use SimpleXMLElement;
 
 class Servers
 {
-    /** @var string $frontend */
+    /** @var string|null $frontend */
```
Comment (howard) [inline src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php]: Can this really be `null`?

File: src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php [hunk 9]
```diff
@@ -2,14 +2,15 @@
...
     private $frontend;
 
-    /** @var string $backend */
+    /** @var string|null $backend */
```
Comment (howard) [inline src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php]: Can this really be `null`?

File: src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php [hunk 10]
```diff
@@ -18,20 +19,20 @@ class Servers
...
     {
-        $this->frontend = (string)$response->frontend;
-        $this->backend = (string)$response->backend;
+        $this->frontend = ResponseHelper::getProperty($response, 'frontend', 'string');
+        $this->backend = ResponseHelper::getProperty($response, 'backend', 'string');
     }
 
     /**
-     * @return string
+     * @return string|null
```
Comment (howard) [inline src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php]: Can this really be `null`?

File: src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php [hunk 11]
```diff
@@ -18,20 +19,20 @@ class Servers
...
      */
     public function getFrontend()
     {
         return $this->frontend;
     }
 
     /**
-     * @return string
+     * @return string|null
```
Comment (howard) [inline src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php]: Can this really be `null`?

File: tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+        $this->assertTrue(is_int($propertyValue));
+    }
+
+    public function testGetPropertyWillThrowAnExceptionIfSubmittingAnUncastableType()
+    {
+        $expectedPropertyValue = new stdClass();
+        $this->testObject->something = $expectedPropertyValue;
+        try {
+            $propertyValue = ResponseHelper::getProperty($this->testObject, 'something', 'int');
+            $this->fail('An Exception was expected to occur if an uncastable type is submitted.');
```
Comment (howard) [inline tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php]: Can we use `@expectedException` and `@expectedExceptionMessage` instead?

File: tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+        }
+    }
+
+    public function testGetPropertyWillThrowAnExceptionIfSubmittingAnUnknownType()
+    {
+        $expectedPropertyValue = 'blubbergurken';
+        $this->testObject->something = $expectedPropertyValue;
+        try {
+            $propertyValue = ResponseHelper::getProperty($this->testObject, 'something', 'olo');
+            $this->fail('An Exception was expected to occur if an unknown type is submitted.');
```
Comment (howard) [inline tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php]: Can we use `@expectedException` and `@expectedExceptionMessage` instead?

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 2 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: Actually it is `object`.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 3 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: Good catch. I do not know why this was like that. I changed it to `FINDOLOGIC\Api`

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 4 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: Why would that be an improvement? How can something exist in my API Wrapper that does not exist in the actual XML response?  
Let's say I want to get the color of an `Item`, this means I need to call `$item->getColor()`. What do I expect an empty string or `null`, which tells the consumer "Hey I do not have a color"?  

I am not sure, but maybe the best way is to make this configurable via the FINDOLOGIC API Config? But I am up for discussion ;).

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 5 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: This case may happen if a property exists, but is `''`. For example if I have a suggestion response and of course not all suggestions do have an image URL since some of them may be text suggestions or category suggestions. In this case I want to return `null` if somebody tries to actually want to get the image of the suggestion.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 6 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: They are redundant, but I'd like to keep them, because usually when a condition has parentheses it is most of the time a boolean.

File: src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php (hunk 8 above)
Comment (TheKeymaster) [reply src/FINDOLOGIC/Objects/XmlResponseObjects/Servers.php]: Based on the code, it potentially could. But only if FINDOLOGIC would not send this data. Since this will never happen anyway, I will remove that information from the docblock.

File: tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php (hunk 12 above)
Comment (TheKeymaster) [reply tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php]: We could but since this is deprecated soon, I'd like not to :).

File: tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php (hunk 13 above)
Comment (TheKeymaster) [reply tests/FINDOLOGIC/Tests/Helpers/ResponseHelperTest.php]: We could but since this is deprecated soon, I'd like not to :).

**Comment by TheKeymaster** [comment]
@howard I would be ready for a second round.

File: src/FINDOLOGIC/Helpers/ResponseHelper.php (hunk 5 above)
Comment (howard) [reply src/FINDOLOGIC/Helpers/ResponseHelper.php]: Optional fields that just exist for some kinds of suggestions could be implemented by having a smart class hierarchy with different fields for whatever is needed.

For a consumer of objects of these classes it's also handy, because they don't have to null-check on their end, and they can use the type of the object to determine how to display it.
